name:                cds
version:             0.1.0.0
github:              "githubuser/cds"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/cds#readme>

dependencies:
  - base >= 4.10 && < 5
  - JuicyPixels >= 3.3.5

library:
  source-dirs: src
  dependencies:
    - accelerate >= 1.3.0.0
    - accelerate-llvm >= 1.3.0.0
    - accelerate-llvm-native >= 1.3.0.0
    - constraints-deriving >=1.1.1.2
    - JuicyPixels >= 3.3.5
    - optparse-applicative >= 0.16
    - singletons >= 3.0
    - singletons-th >= 3.0
    - singletons-base >= 3.0
    - typenums >= 0.1.4
    - vector >= 0.12.3.0

executables:
  cds:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O
    dependencies:
      - cds


tests:
  cds-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cds
